[package]
name = "ghostframe-xdaemon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
ghostframe-lib = { path = "../ghostframe-lib" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
drm = "0.14"
libc = { workspace = true }
x11rb = { version = "0.13", features = ["damage", "xtest"] }
