#ifndef GHOSTFRAME_CLIENT_H
#define GHOSTFRAME_CLIENT_H

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result code returned by every fallible `gf_*` call.
 */
typedef enum gf_result {
  GF_OK = 0,
  /**
   * Nothing is available right now (no queued event, no ready frame).
   * Not an error -- callers poll again later.
   */
  GF_AGAIN = 1,
  /**
   * A null pointer, a wrong `struct_size`, or another malformed
   * argument. Also returned when a call caught an internal panic (see
   * the module doc on `lib.rs` for why no panic may cross the FFI
   * boundary).
   */
  GF_ERR_INVALID = 2,
  /**
   * The call is not valid for the client's current state (e.g.
   * `connect` called twice).
   */
  GF_ERR_STATE = 3,
  GF_ERR_IO = 4,
  GF_ERR_GPU = 5,
} gf_result;

typedef enum gf_event_type {
  GF_EVENT_CONNECTED = 0,
  GF_EVENT_DISCONNECTED = 1,
  GF_EVENT_RESIZED = 2,
  GF_EVENT_FRAME_READY = 3,
  GF_EVENT_ERROR = 4,
} gf_event_type;

/**
 * How to interpret [`gf_frame::planes`].
 */
typedef enum gf_handle_type {
  /**
   * Linux dmabuf: `gf_plane::fd` is a PRIME fd. The only type M1
   * produces.
   */
  GF_HANDLE_DMABUF = 0,
  GF_HANDLE_WIN32_NT = 1,
  GF_HANDLE_IOSURFACE = 2,
  GF_HANDLE_CPU = 3,
} gf_handle_type;

/**
 * The opaque handle behind every `gf_client *`.
 *
 * Wraps the real [`Client`] plus the one piece of state this shim layer
 * owns itself: a per-`frame_id` stash of the converted [`gf_rect`] damage
 * list, so [`gf_frame::damage`] has somewhere stable to point until
 * [`gf_client_release_frame`] frees it. `ghostframe_client_native::Client::acquire_frame`
 * hands back an owned `Vec` that would otherwise be dropped the instant
 * this call returns.
 */
typedef struct gf_client gf_client;

/**
 * Configuration for [`crate::gf_client_create`].
 *
 * `struct_size` MUST be set to `sizeof(gf_client_config)` by the caller;
 * it is the forward-compatibility mechanism that lets a future ABI
 * revision add fields without breaking a caller built against an older
 * header. `struct_size` smaller than this library understands the fields
 * up to (see [`Self::max_decode_width`]'s doc) is rejected with
 * `GF_ERR_INVALID`; a `struct_size` that covers the original fields but
 * not a later addition is accepted, with the addition's fields read as
 * whatever default that field's own doc names (never misread from
 * unallocated memory).
 */
typedef struct gf_client_config {
  uint32_t struct_size;
  const char *hostname;
  const char *state_dir;
  const char *authkey;
  /**
   * A *request*, not an assertion: whether the host wants H.264 decode if
   * this machine can do it. `gf_client_supports_h264` returns the answer
   * -- a host that asks for H.264 on a machine without VA-API gets
   * `false` there and a working session on the tile codecs, not a
   * failure.
   */
  bool supports_h264;
  bool indices_raw;
  /**
   * `0` means "use the library's default" (currently 3).
   */
  uint32_t n_export_buffers;
  uint32_t n_preferred_modifiers;
  /**
   * Array of `n_preferred_modifiers` `u64`s, most-preferred first. May
   * be null when `n_preferred_modifiers == 0`.
   */
  const uint64_t *preferred_modifiers;
  /**
   * This client's own maximum display resolution (its screen, or
   * eventually its negotiated virtual EDID) -- NOT the session's current
   * frame size, which arrives separately over the wire. Appended after
   * `preferred_modifiers`, so a caller built against a header from
   * before this field existed reports a smaller `struct_size` and gets
   * `0` read here rather than a rejected config -- see this struct's own
   * doc. `0` in either `max_decode_width` or `max_decode_height` means
   * "unknown, do not pre-warm", identical to what an old caller gets by
   * construction: the H.264 decoder opens lazily on the first H.264
   * frame instead of being pre-warmed in `gf_client_create`. See
   * `ghostframe_client_native::Config::max_decode_width`.
   */
  uint32_t max_decode_width;
  uint32_t max_decode_height;
} gf_client_config;

/**
 * One event popped by [`crate::gf_client_next_event`].
 *
 * `struct_size` MUST be set to `sizeof(gf_event)` by the caller before
 * the call -- see [`gf_client_config`]'s doc for why.
 */
typedef struct gf_event {
  uint32_t struct_size;
  enum gf_event_type kind;
  /**
   * Valid for `GF_EVENT_RESIZED`.
   */
  uint32_t width;
  /**
   * Valid for `GF_EVENT_RESIZED`.
   */
  uint32_t height;
  /**
   * Valid for `GF_EVENT_FRAME_READY`.
   */
  uint32_t frame_id;
  /**
   * Valid for `GF_EVENT_DISCONNECTED` and `GF_EVENT_ERROR`. NUL-terminated,
   * truncated to 255 bytes + NUL if the underlying message is longer.
   * A fixed inline buffer rather than an owned pointer deliberately: a
   * `const char *` here would need its own ownership rule and free
   * function for what is only ever a short diagnostic string.
   */
  char message[256];
} gf_event;

/**
 * One plane of a [`gf_frame`]'s image data.
 *
 * ## Ownership
 *
 * `fd` is owned by the library and remains valid until the `gf_client` is
 * destroyed. The caller must NOT close it -- `dup(2)` it first if a
 * longer-lived handle is needed than the frame it arrived on.
 */
typedef struct gf_plane {
  int32_t fd;
  uint32_t offset;
  uint32_t stride;
} gf_plane;

/**
 * A damaged rectangle, in pixel coordinates.
 */
typedef struct gf_rect {
  uint32_t x;
  uint32_t y;
  uint32_t w;
  uint32_t h;
} gf_rect;

/**
 * One decoded frame, ready for the host to import and present.
 *
 * ## Ownership
 *
 * - `planes[i].fd`: owned by the library, valid until the `gf_client` is
 *   destroyed. Do not close it; `dup(2)` for a longer life.
 * - `acquire_fence_fd`: owned by the CALLER, who must close it. Always
 *   `-1` in M1 (the frame is already signalled by the time
 *   `gf_client_acquire_frame` returns it -- there is no fence to wait on
 *   yet).
 * - `damage`: points into library memory. Valid only until the matching
 *   `gf_client_release_frame` call; do not retain the pointer past it.
 */
typedef struct gf_frame {
  uint32_t struct_size;
  uint32_t frame_id;
  uint32_t buffer_id;
  enum gf_handle_type handle_type;
  uint32_t width;
  uint32_t height;
  uint64_t drm_modifier;
  uint32_t n_planes;
  struct gf_plane planes[4];
  int32_t acquire_fence_fd;
  uint32_t n_damage;
  const struct gf_rect *damage;
} gf_frame;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * `cfg` must be null, or point to at least `cfg.struct_size` readable
 * bytes laid out as a prefix of `gf_client_config` -- i.e. a struct built
 * against this exact header, or an older header that had fewer trailing
 * fields (see [`gf_client_config`]'s doc on `struct_size`).
 * `out` must be null or point to a valid, writable `*mut gf_client`.
 */
enum gf_result gf_client_create(const struct gf_client_config *cfg, struct gf_client **out);

/**
 * # Safety
 * `c` must be null or a pointer previously returned by
 * [`gf_client_create`] and not yet passed to `gf_client_destroy`.
 */
void gf_client_destroy(struct gf_client *c);

/**
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
int32_t gf_client_event_fd(const struct gf_client *c);

/**
 * The H.264 capability the client actually advertised.
 *
 * `gf_client_config.supports_h264` is a *request*; this is the *answer*. A
 * host that asked for H.264 on a machine without VA-API gets `false` here
 * and a working session on the tile codecs.
 *
 * Returns `false` for a null client.
 *
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
bool gf_client_supports_h264(const struct gf_client *c);

/**
 * Never blocks. Returns `GF_AGAIN` when the queue is empty.
 *
 * # Safety
 * `c` and `out` must each be null or point to valid memory as documented
 * on their types.
 */
enum gf_result gf_client_next_event(struct gf_client *c, struct gf_event *out);

/**
 * # Safety
 * `c` and `host` must each be null or point to valid memory as documented
 * on their types; `host` must be NUL-terminated.
 */
enum gf_result gf_client_connect(struct gf_client *c, const char *host, uint16_t port);

/**
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
enum gf_result gf_client_disconnect(struct gf_client *c);

/**
 * Never blocks. Returns `GF_AGAIN` when no frame is ready.
 *
 * # Safety
 * `c` and `out` must each be null or point to valid memory as documented
 * on their types.
 */
enum gf_result gf_client_acquire_frame(struct gf_client *c, struct gf_frame *out);

/**
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
void gf_client_release_frame(struct gf_client *c, uint32_t frame_id);

/**
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
enum gf_result gf_client_push_pointer_motion(struct gf_client *c, int16_t x, int16_t y);

/**
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
enum gf_result gf_client_push_pointer_button(struct gf_client *c,
                                             int16_t x,
                                             int16_t y,
                                             uint8_t button,
                                             bool down);

/**
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
enum gf_result gf_client_push_wheel(struct gf_client *c, int16_t dx, int16_t dy);

/**
 * # Safety
 * `c` must be null or a valid, live `gf_client` pointer.
 */
enum gf_result gf_client_push_key(struct gf_client *c, uint32_t keysym, bool down);

/**
 * # Safety
 * `major`, `minor` and `patch` must each be null or a valid, writable
 * `u32` pointer.
 */
void gf_version(uint32_t *major, uint32_t *minor, uint32_t *patch);

/**
 * # Safety
 * Callable with any `gf_result` value; marked `unsafe` for consistency
 * with the rest of this crate's `extern "C"` surface, not because this
 * particular function dereferences anything unchecked.
 */
const char *gf_result_str(enum gf_result r);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GHOSTFRAME_CLIENT_H */
