//! Sans-IO QUIC + WebTransport client session wrapping `ClientCore`.
//!
//! There is deliberately no dial API and no socket code in this crate: the
//! embedder supplies the byte pump. In production that pump is ghostbridge's
//! `dial_udp` through tsnet, so a client can never escape the tailnet; in
//! tests it is the netsim.

mod clock;
mod endpoint;
mod event;
mod handshake;
pub mod tls;

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use bytes::{Bytes, BytesMut};
use ghostframe_client_core::{ClientConfig, ClientCore, PollOutput};
use quinn_proto::{Dir, StreamId, TransportConfig};
use web_transport_proto::VarInt;

use clock::Instant;
use endpoint::ClientEndpoint;
use handshake::{ConnectOutcome, WebTransportHandshake};

pub use event::{ClientNetError, ClientNetEvent, UdpOut};

#[derive(Debug, Clone)]
pub struct ClientNetConfig {
    /// SNI name presented in the TLS handshake.
    pub server_name: String,
    /// The only certificate this client will accept, by SHA-256 of its DER.
    pub server_cert_sha256: [u8; 32],
    pub indices_raw_enabled: bool,
    pub supports_h264: bool,
}

pub struct ClientNet {
    config: ClientNetConfig,
    connected: bool,
    /// The WebTransport CONNECT was accepted (status 200): datagrams may
    /// now flow both ways. Mirrors `WebTransportServer`'s own `connected`
    /// gate on `recv_datagram`/`send_datagram` (`webtransport.rs:262`,
    /// `:288`) so a datagram arriving (or being generated by `core`) before
    /// the session is live is never mistaken for tile traffic.
    session_ready: bool,
    /// `PollOutput::Stream` payloads (Hello, ReceiverFeedback, DecodeError)
    /// drained from `core` before the feedback stream exists to carry them
    /// (i.e. before `SessionReady`, which is when `feedback_stream` is
    /// opened). The Hello queued by `ClientCore::new` is the only payload
    /// that can accumulate here in practice — everything else `core`
    /// produces is itself triggered by post-session traffic — but the
    /// buffer stays generic so any output racing the stream-open is still
    /// carried rather than dropped.
    pending_stream_out: Vec<Vec<u8>>,
    /// Bidirectional stream carrying every `PollOutput::Stream` payload
    /// (Hello, ReceiverFeedback, DecodeError) to the server. Opened once,
    /// right after `SessionReady`: the server routes data arriving on any
    /// bidi stream other than the session stream to its feedback queue
    /// (`WebTransportServer::try_decode_connect`,
    /// `webtransport.rs:362-372`), so no further handshake is needed on
    /// this stream — the first write is itself the signal.
    feedback_stream: Option<StreamId>,
    endpoint: ClientEndpoint,
    handshake: WebTransportHandshake,
    /// Sans-IO tile reassembly/decode state machine. Datagram payloads
    /// (quarter-stream-id prefix already stripped) go in via
    /// `handle_datagram`; `TileReady`/`DecodeError`/... come back out as
    /// `ClientNetEvent::Core`. See `drain_connection_events` for the wiring.
    core: ClientCore,
    events: Vec<ClientNetEvent>,
    /// Wall-clock anchor captured once at construction. Every other piece of
    /// timing in this crate is injected microseconds (`now_us`); this is the
    /// sole `Instant::now()` call, needed only because quinn-proto's API is
    /// expressed in `Instant`, not because the crate tracks real time itself.
    /// See the "Wasm" note on `ClientNet::new` for why this is safe to build
    /// on `wasm32-unknown-unknown`.
    base: Instant,
}

impl ClientNet {
    /// `now_us` seeds `ClientCore`'s internal deadlines (assembly timeout,
    /// tail sweep, feedback cadence — see `ClientCore::new`); it is
    /// otherwise unused here (there is nothing else to schedule before
    /// `connect`), but is accepted for symmetry with the rest of this
    /// crate's injected-time API and so a future revision can seed other
    /// `base`-relative state without changing the signature.
    ///
    /// Wasm note: bare `std::time::Instant::now()` panics on
    /// `wasm32-unknown-unknown`. `Instant` here is `crate::clock::Instant`,
    /// which is `std::time::Instant` on every target except wasm, where it
    /// is `web_time::Instant` (backed by `Performance.now()` via
    /// `wasm-bindgen`) — the same conditional type quinn-proto itself picks
    /// internally, which is why this crate has to mirror it rather than pick
    /// its own. This is the only place in the crate that calls `::now()`;
    /// every other method takes `now_us: u64` and derives an `Instant` from
    /// `base`, so the wasm/native split is confined to `clock.rs` and this
    /// one call site.
    pub fn new(config: ClientNetConfig, now_us: u64) -> Result<Self, ClientNetError> {
        let core = ClientCore::new(
            ClientConfig {
                indices_raw_enabled: config.indices_raw_enabled,
                supports_h264: config.supports_h264,
            },
            now_us,
        );
        Ok(Self {
            config,
            connected: false,
            session_ready: false,
            pending_stream_out: Vec::new(),
            feedback_stream: None,
            endpoint: ClientEndpoint::new(),
            handshake: WebTransportHandshake::new(),
            core,
            events: Vec::new(),
            base: Instant::now(),
        })
    }

    fn instant(&self, now_us: u64) -> Instant {
        self.base + Duration::from_micros(now_us)
    }

    /// Name the peer for quinn-proto's state machine and start the QUIC
    /// handshake. This does not open a socket — it only tells quinn-proto
    /// which `SocketAddr` outbound datagrams should be addressed to; the
    /// embedder's byte pump (tsnet's `dial_udp` in production, the netsim in
    /// tests) is what actually moves bytes.
    pub fn connect(&mut self, remote: SocketAddr, now_us: u64) -> Result<(), ClientNetError> {
        let now = self.instant(now_us);

        let verifier = Arc::new(tls::PinnedCertVerifier::new(self.config.server_cert_sha256));
        let provider = Arc::new(rustls::crypto::ring::default_provider());
        let mut client_tls = rustls::ClientConfig::builder_with_provider(provider)
            .with_safe_default_protocol_versions()
            .map_err(|e| ClientNetError::Tls(e.to_string()))?
            .dangerous()
            .with_custom_certificate_verifier(verifier)
            .with_no_client_auth();
        client_tls.alpn_protocols = vec![b"h3".to_vec()];

        let quic_client_tls = quinn_proto::crypto::rustls::QuicClientConfig::try_from(client_tls)
            .map_err(|e| ClientNetError::Tls(e.to_string()))?;

        let mut transport = TransportConfig::default();
        transport.datagram_receive_buffer_size(Some(65536));
        transport.datagram_send_buffer_size(65536);

        let mut client_config = quinn_proto::ClientConfig::new(Arc::new(quic_client_tls));
        client_config.transport_config(Arc::new(transport));

        self.endpoint
            .connect(now, client_config, remote, &self.config.server_name)
            .map_err(|e| ClientNetError::Connect(e.to_string()))?;

        // Flush the Initial packet produced by `connect` into the outbound
        // queue so the first call to `poll_transmit` has something to give
        // the byte pump.
        self.endpoint.drive_outgoing(now);
        self.drain_connection_events(now_us);

        Ok(())
    }

    /// Feed one inbound datagram (received by the embedder's byte pump) into
    /// the QUIC state machine.
    pub fn handle_udp(&mut self, data: &[u8], remote: SocketAddr, now_us: u64) {
        let now = self.instant(now_us);
        self.endpoint
            .drive_incoming(now, remote, None, BytesMut::from(data));
        self.endpoint.drive_outgoing(now);
        self.drain_connection_events(now_us);
    }

    /// Poll `quinn_proto::Event`s off the active connection and translate
    /// the ones this crate currently understands into `ClientNetEvent`s.
    ///
    /// `Connected` kicks off the WebTransport handshake (opens the SETTINGS
    /// and CONNECT streams); `Stream(StreamEvent::Readable)` on the session
    /// stream drives it forward until the CONNECT response decodes.
    /// `DatagramReceived` feeds inbound tile datagrams to `ClientCore`; once
    /// every polled event has been handled, any output `core` queued as a
    /// side effect (ACKs, NACKs, ...) is flushed out as WebTransport
    /// datagrams too — see `flush_core_outbox`.
    fn drain_connection_events(&mut self, now_us: u64) {
        let Some(conn) = self.endpoint.connection() else {
            return;
        };
        while let Some(event) = conn.poll() {
            match event {
                quinn_proto::Event::Connected => {
                    self.connected = true;
                    self.events.push(ClientNetEvent::Connected);
                    if let Err(e) = self.handshake.start(conn, &self.config.server_name) {
                        self.events.push(ClientNetEvent::ConnectionLost {
                            reason: e.to_string(),
                        });
                    }
                }
                quinn_proto::Event::Stream(quinn_proto::StreamEvent::Readable { id }) => {
                    if self.handshake.session_stream() == Some(id) {
                        match self.handshake.on_readable(conn, id) {
                            ConnectOutcome::Pending => {}
                            ConnectOutcome::Accepted => {
                                self.session_ready = true;
                                self.events.push(ClientNetEvent::SessionReady);
                            }
                            ConnectOutcome::Rejected(reason) => {
                                self.events.push(ClientNetEvent::ConnectionLost { reason });
                            }
                        }
                    }
                }
                quinn_proto::Event::DatagramReceived => {
                    // Mirrors `WebTransportServer::recv_datagram`'s gate:
                    // before the session is accepted, a datagram cannot be
                    // tile traffic (the real server never sends any that
                    // early either — see `send_datagram`'s own `connected`
                    // check), so leave it queued in quinn-proto rather than
                    // guess at how to interpret it.
                    if !self.session_ready {
                        continue;
                    }
                    while let Some(raw) = conn.datagrams().recv() {
                        let mut slice: &[u8] = &raw;
                        // Strip the quarter-stream-id VarInt prefix (RFC
                        // 9297), the same framing `send_datagram` on the
                        // server side prepends (`webtransport.rs:288-305`).
                        match VarInt::decode(&mut slice) {
                            Ok(_quarter_id) => {
                                for e in self.core.handle_datagram(slice, now_us) {
                                    self.events.push(ClientNetEvent::Core(e));
                                }
                            }
                            Err(e) => {
                                tracing::warn!(
                                    error = ?e,
                                    "datagram VarInt prefix decode failed"
                                );
                            }
                        }
                    }
                }
                quinn_proto::Event::ConnectionLost { reason } => {
                    self.connected = false;
                    self.events.push(ClientNetEvent::ConnectionLost {
                        reason: reason.to_string(),
                    });
                }
                _ => {}
            }
        }

        // Flush every `PollOutput` `core` queued as a side effect of the
        // events just processed (ACKs, NACKs, ...) back out over the
        // WebTransport session.
        //
        // Only `PollOutput::Datagram` is handled: it is prepended with the
        // quarter-stream-id VarInt prefix (mirroring `send_datagram` on the
        // server, `webtransport.rs:288-305`) and handed to
        // `conn.datagrams().send(.., false)`. The `false` matters and is
        // not quinn-proto's default: it matches the server's non-dropping
        // behaviour, so a full send buffer surfaces as `Blocked` instead of
        // silently discarding the oldest queued datagram (see
        // `webtransport.rs:294-302` for why silent drop is the wrong choice
        // here — it made server-side loss invisible to the receiver's
        // `loss_rate`).
        //
        // `PollOutput::Stream` (Hello, ReceiverFeedback, DecodeError) is
        // held in `pending_stream_out` rather than written immediately: it
        // must still be drained here, because leaving it queued in `core`
        // would block every `Datagram` output behind it in the same
        // `VecDeque`, but the feedback stream this crate writes it to may
        // not be open yet (it opens on `SessionReady`, below). `ClientCore::
        // new` queues the Hello (carrying the client's caps) at
        // construction, so dropping outputs here would lose it before a
        // feedback stream ever exists and the server would never learn what
        // this client supports.
        //
        // This is inlined here (rather than split into a `&mut self`
        // helper method) because `conn` already holds a live borrow of
        // `self.endpoint`'s internals: a helper taking `&mut self` would
        // need to reborrow all of `self`, which conflicts with that.
        // `self.handshake` / `self.core` are disjoint fields from
        // `self.endpoint`, so borrowing them individually alongside the
        // already-borrowed `conn` is fine.
        if self.session_ready {
            if let Some(session_stream) = self.handshake.session_stream() {
                let quarter_id = VarInt::from_u64(u64::from(session_stream) / 4)
                    .expect("stream id / 4 always fits in VarInt");

                while let Some(output) = self.core.poll_transmit(now_us) {
                    match output {
                        PollOutput::Datagram(payload) => {
                            let mut buf = BytesMut::new();
                            quarter_id.encode(&mut buf);
                            buf.extend_from_slice(&payload);
                            if let Err(e) = conn.datagrams().send(Bytes::from(buf), false) {
                                tracing::warn!(error = ?e, "outbound datagram send failed");
                            }
                        }
                        PollOutput::Stream(bytes) => {
                            self.pending_stream_out.push(bytes);
                        }
                    }
                }
            }

            // Open the feedback stream the first time the session is ready
            // (i.e. once, ever, per connection) so the server has something
            // other than the session stream to route non-session bidi data
            // to (see `feedback_stream`'s doc comment). Opening it here,
            // after the `poll_transmit` drain above, means the very first
            // write on it — on the same call that flips `session_ready` —
            // can already include the Hello that's been waiting in
            // `pending_stream_out` since construction.
            if self.feedback_stream.is_none() {
                match conn.streams().open(Dir::Bi) {
                    Some(sid) => self.feedback_stream = Some(sid),
                    None => tracing::warn!(
                        "stream limit reached opening the feedback stream; \
                         Hello/ReceiverFeedback/DecodeError will queue until one frees up"
                    ),
                }
            }
            if let Some(sid) = self.feedback_stream {
                for bytes in self.pending_stream_out.drain(..) {
                    if let Err(e) = conn.send_stream(sid).write(&bytes) {
                        tracing::warn!(error = ?e, "feedback stream write failed");
                    }
                }
            }
        }

        // `conn`'s borrow of `self.endpoint` ends here (its last use was
        // above): re-borrow to turn whatever `core` just queued via
        // `conn.datagrams().send()` into an actual `Transmit` in
        // `self.endpoint`'s outbound queue. Without this second call, a
        // datagram `core` generates as a *side effect* of handling an
        // inbound one (e.g. an ACK) would sit unsent inside quinn-proto
        // until some unrelated later `handle_udp` happened to call
        // `drive_outgoing` again.
        let now = self.instant(now_us);
        self.endpoint.drive_outgoing(now);
    }

    pub fn is_connected(&self) -> bool {
        self.connected
    }

    /// Drain and return every event accumulated since the last call. Events
    /// can be produced by a timer expiry inside `drive_outgoing` as well as
    /// by an inbound datagram, so this single drain point (rather than a
    /// return value on `handle_udp`) is the only way callers are guaranteed
    /// not to miss one.
    pub fn take_events(&mut self) -> Vec<ClientNetEvent> {
        std::mem::take(&mut self.events)
    }

    pub fn poll_transmit(&mut self) -> Option<UdpOut> {
        let (transmit, bytes) = self.endpoint.pop_outbound()?;
        Some(UdpOut {
            payload: bytes.to_vec(),
            destination: transmit.destination,
        })
    }

    pub fn server_name(&self) -> &str {
        &self.config.server_name
    }
}
